load_images:
  path: ['data', 'train_images']

  images:
    target_actors: [ 'Angelina Jolie', 'Helena Bonham Carter', 'Jennifer Aniston',
                     'Julia Roberts', 'Kate Beckinsale', 'Keira Knightley', 'Lindsey Stirling',
                     'Marilyn Monroe', 'Monica Bellucci', 'Lucy Liu', 'Scarlett Johansson',
                     'Henry Cavill', 'Matthew McConaughey', 'Timothee Chalamet', 'Chris Hemsworth',
                     'Xiao Zhan', 'Johnny Depp', 'Cristiano Ronaldo', 'Tom Hiddleston',
                     'Lucien Leon Laviscount', 'Ryan Reynolds', 'Brad Pitt']
    size_new: 256
    limit: 20

model:
  path: ['data', 'model_data']
  name: 'model_LR.pkl'
  random_state: 13
  test_size: 0.25
  coef_C: 1.0
  key_load_train_images: False

predict:
  size_image_users: 512
  path: ['data', 'users_image']
