load_images:
  path: ['data', 'train_images']

  images:
    target_actors: [ 'Angelina Jolie', 'Helena Bonham Carter', 'Jennifer Aniston',
                     'Julia Roberts', 'Kate Beckinsale', 'Keira Knightley', 'Lindsey Stirling',
                     'Marilyn Monroe', 'Monica Bellucci', 'Lucy Liu', 'Scarlett Johansson' ]
    size_new: 256
    limit: 15

model:
  path: ['data', 'model_data']
  random_state: 13
  test_size: 0.25
  coef_C: 1.0
  key_load_images: False

predict:
  size_image_users: 1024
  path: ['data', 'user_photo']
